### ISSUE TITLE
app todo

### ISSUE THREAD

**Issue by diebolo** [remla24-team8/app-service#1]
The application has a frontend and a service, which can, but do not have to, be implemented separately. The
application uses the model service in a sensible use case.

- [x] Depends on the lib-version through a package manager (e.g., Maven). The version is visible in the frontend.
- [x] Queries the model-service through REST requests.
- [x] The URL of the model-service is configurable as an environment variable.
